version: '3.7'
services:
  app-prod:
    container_name: ${CI_PROJECT_NAME}
    profiles: ["prod"]
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    image: ${CI_REGISTRY_IMAGE:-storybook-devfactory}:${CI_COMMIT_SHORT_SHA:-latest}  
    ports:
      - ${PORT:-6007}:6006
  app-dev:
    container_name: storybook-devFactory-dev
    profiles: ["dev"]
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    command: yarn run storybook
    volumes:
      - ./:/app:cached
      - /app/node_modules
    ports:
      - 6008:6006